/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultRouteImport } from './routes/result'
import { Route as PlayPrecisionRouteImport } from './routes/play.precision'
import { Route as PlayReactionRouteImport } from './routes/play.reaction'
import { Route as PlayRhythmRouteImport } from './routes/play.rhythm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPrecisionRoute = PlayPrecisionRouteImport.update({
  id: '/play/precision',
  path: '/play/precision',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayReactionRoute = PlayReactionRouteImport.update({
  id: '/play/reaction',
  path: '/play/reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRhythmRoute = PlayRhythmRouteImport.update({
  id: '/play/rhythm',
  path: '/play/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/play/precision': typeof PlayPrecisionRoute
  '/play/reaction': typeof PlayReactionRoute
  '/play/rhythm': typeof PlayRhythmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/play/precision': typeof PlayPrecisionRoute
  '/play/reaction': typeof PlayReactionRoute
  '/play/rhythm': typeof PlayRhythmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/play/precision': typeof PlayPrecisionRoute
  '/play/reaction': typeof PlayReactionRoute
  '/play/rhythm': typeof PlayRhythmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/leaderboard'
    | '/match'
    | '/profile'
    | '/result'
    | '/play/precision'
    | '/play/reaction'
    | '/play/rhythm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/leaderboard'
    | '/match'
    | '/profile'
    | '/result'
    | '/play/precision'
    | '/play/reaction'
    | '/play/rhythm'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/leaderboard'
    | '/match'
    | '/profile'
    | '/result'
    | '/play/precision'
    | '/play/reaction'
    | '/play/rhythm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchRoute: typeof MatchRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  PlayPrecisionRoute: typeof PlayPrecisionRoute
  PlayReactionRoute: typeof PlayReactionRoute
  PlayRhythmRoute: typeof PlayRhythmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/precision': {
      id: '/play/precision'
      path: '/play/precision'
      fullPath: '/play/precision'
      preLoaderRoute: typeof PlayPrecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/reaction': {
      id: '/play/reaction'
      path: '/play/reaction'
      fullPath: '/play/reaction'
      preLoaderRoute: typeof PlayReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/rhythm': {
      id: '/play/rhythm'
      path: '/play/rhythm'
      fullPath: '/play/rhythm'
      preLoaderRoute: typeof PlayRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchRoute: MatchRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  PlayPrecisionRoute: PlayPrecisionRoute,
  PlayReactionRoute: PlayReactionRoute,
  PlayRhythmRoute: PlayRhythmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
